### ISSUE TITLE
package android_alarm_manager_plus breaks the example code

### ISSUE THREAD

**Issue by k2s** [Rexios80/polar#28]
adding android_alarm_manager_plus package and calling `AndroidAlarmManager.initialize()` to the example stops it from working

- the call `await polar.sdkFeatureReady.firstWhere(...)` will never finish
- `deviceConnecting.listen` and other events will not be fired
- `searchForDevice()` is able to detect the H10 device

**Comment by Rexios80** [comment]
It seems that android_alarm_manager is discontinued. Did you try [android_alarm_manager_plus](https://pub.dev/packages/android_alarm_manager_plus)?

**Comment by Rexios80** [comment]
This should fixed by version `7.3.0`

I created an issue to fix the root cause of this here: https://github.com/flutter/flutter/issues/69721

**Comment by Aakash1111** [comment]
> This should fixed by version `7.3.0`
> 
> I created an issue to fix the root cause of this here: [flutter/flutter#150674](https://github.com/flutter/flutter/issues/150674)

@Rexios80  - Still not working, no devices listing on searchForDevice() method call.

**Comment by Rexios80** [comment]
Try this

```yaml
dependency_overrides:
  polar:
    git:
      url: https://github.com/Rexios80/polar
      ref: c490d7044559825224d2127f2ef650e6834210a5
```

**Comment by Rexios80** [comment]
@Aakash1111 Please let me know if that solution works for you so I can release it

**Comment by k2s** [comment]
for me this is fixed in version 7.3.0
